import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import * as React from "react";

interface ReportEmailProps {
  score: number;
  urgentCount: number;
  warningCount: number;
  infoCount: number;
  penaltyMax: number;
}

function scoreLabel(score: number): string {
  if (score < 30) return "Critical";
  if (score < 50) return "Poor";
  if (score < 70) return "Needs Work";
  if (score < 85) return "Good";
  return "Excellent";
}

function formatCurrency(amount: number): string {
  if (amount >= 1000) return `$${(amount / 1000).toFixed(0)}K`;
  return `$${amount.toLocaleString()}`;
}

export default function ReportEmail({
  score,
  urgentCount,
  warningCount,
  infoCount,
  penaltyMax,
}: ReportEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>{`Your NRI Compliance Report (Score: ${score}/100)`}</Preview>
      <Body style={bodyStyle}>
        <Container style={containerStyle}>
          <Heading style={headingStyle}>Your NRI Compliance Report</Heading>

          <Section style={scoreBoxStyle}>
            <Text style={scoreBigStyle}>{score}/100</Text>
            <Text style={scoreLabelStyle}>{scoreLabel(score)}</Text>
          </Section>

          <Section style={summaryStyle}>
            <Text style={summaryTextStyle}>
              {urgentCount > 0 && `${urgentCount} urgent issue${urgentCount > 1 ? "s" : ""}`}
              {urgentCount > 0 && (warningCount > 0 || infoCount > 0) ? " | " : ""}
              {warningCount > 0 && `${warningCount} warning${warningCount > 1 ? "s" : ""}`}
              {warningCount > 0 && infoCount > 0 ? " | " : ""}
              {infoCount > 0 && `${infoCount} info item${infoCount > 1 ? "s" : ""}`}
            </Text>
            {penaltyMax > 0 && (
              <Text style={penaltyStyle}>
                Up to {formatCurrency(penaltyMax)} in potential penalties
              </Text>
            )}
          </Section>

          <Hr style={hrStyle} />

          <Text style={bodyTextStyle}>
            Your detailed PDF compliance report is attached to this email. It
            includes all identified issues, why they apply to you, potential
            consequences, and step-by-step fix instructions.
          </Text>

          <Text style={bodyTextStyle}>
            Review the report carefully and prioritize the urgent items first.
            Consider consulting a qualified CPA or tax professional for
            personalized advice.
          </Text>

          <Hr style={hrStyle} />

          <Text style={disclaimerStyle}>
            This report is generated by IndiaOS and is for informational
            purposes only. It does not constitute legal or tax advice. Consult a
            qualified professional for your specific situation.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

const bodyStyle: React.CSSProperties = {
  backgroundColor: "#f6f9fc",
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, sans-serif',
};

const containerStyle: React.CSSProperties = {
  backgroundColor: "#ffffff",
  margin: "0 auto",
  padding: "20px 0 48px",
  marginBottom: "64px",
  maxWidth: "560px",
};

const headingStyle: React.CSSProperties = {
  fontSize: "24px",
  letterSpacing: "-0.5px",
  lineHeight: "1.3",
  fontWeight: "700",
  color: "#000000",
  padding: "0 40px",
};

const scoreBoxStyle: React.CSSProperties = {
  padding: "16px 40px",
  textAlign: "center" as const,
};

const scoreBigStyle: React.CSSProperties = {
  fontSize: "48px",
  fontWeight: "700",
  lineHeight: "1",
  margin: "0",
};

const scoreLabelStyle: React.CSSProperties = {
  fontSize: "14px",
  fontWeight: "600",
  color: "#6b7280",
  margin: "4px 0 0 0",
};

const summaryStyle: React.CSSProperties = {
  padding: "0 40px",
  textAlign: "center" as const,
};

const summaryTextStyle: React.CSSProperties = {
  fontSize: "14px",
  color: "#374151",
  margin: "0",
};

const penaltyStyle: React.CSSProperties = {
  fontSize: "14px",
  fontWeight: "700",
  color: "#ef4444",
  margin: "4px 0 0 0",
};

const hrStyle: React.CSSProperties = {
  borderColor: "#e6ebf1",
  margin: "20px 40px",
};

const bodyTextStyle: React.CSSProperties = {
  fontSize: "14px",
  lineHeight: "24px",
  color: "#374151",
  padding: "0 40px",
};

const disclaimerStyle: React.CSSProperties = {
  fontSize: "11px",
  lineHeight: "16px",
  color: "#9ca3af",
  padding: "0 40px",
};
